### PR TITLE
[WIP] Support for constraint domains

### PR DESCRIPTION
**Pull request by joehuchette**
Doesn't do anything yet. Companion to https://github.com/JuliaOpt/PolyJuMP.jl/pull/1

### CODE REVIEW

**Comment by blegat** [comment]
Do we give a default value like `domain=nothing` ?

**Comment by joehuchette** [comment]
Potentially, I'm not sure I have a great understanding of how things should piece together at this level, though (as opposed to in PolyJuMP).

**Comment by blegat** [comment]
Ok let's not put the cart before the horses. For me this PR can be merged :-)

**Comment by joehuchette** [comment]
Do you mean JuliaOpt/PolyJuMP.jl#1 can be merged?

**Comment by blegat** [comment]
No I meant this one so that we can see if PolyJuMP's tests are passing. We can also merge them both at the same time. I guess that if the tests passes on your computer, it will still pass on travis.

**Comment by joehuchette** [comment]
Ah, OK. Do you have a firm grip of how you might do the transformation from domain --> SDP representation? I'm thinking it's something like
```jl
function addpolynonnegativeconstraint(m::JuMP.Model, p, domain::BasicSemiAlgebraicSet)
    Z = getmonomialsforcertificate(p.x)
    for d in domain.p
        s = createnonnegativepoly(m, :Gram, Z)
        q += d*s
    end
    slack = createnonnegativepoly(m, :Gram, Z)
    q = p - slack
    lincons = addpolyeqzeroconstraint(m, q, domain)
    SOSConstraint(slack, lincons, q.x)
end
```
though I'm not sure what the basis for ``s`` should be.

**Comment by blegat** [comment]
It is not clear to me how to decide the monomials for `s`
The fundamental identity is: `N(p*q) = N(p) + N(q)` where p, q are polynomials and `N` is the newton polytope.
From that we have `N(p^2) = 2N(p)`. Moreover, the coefficients of `p^2` corresponding to the extrement points of `N(p^2)` are nonnegative, e.g. `(ax+by) = a^2x^2 + 2abxy + b^2y^2`, we see that `a^2` and `b^2` are nonnegative.
Therefore, `N(p^2)` and `N(q^2)` are included in `N(p^2 + q^2)` since "their extreme points do not cancel" in `p^2 + q^2`.

Here, it is a lot less clear what to do. We have `p = slack + sum s_i * q_i`
but the extreme points of `s_i * q_i` can cancel with the extreme points of `s_j * q_j` (`j != i`) or `slack`.
Therefore, we really cannot make any sparsity reduction on `slack` or `s_i` in general I think...
What is usually do though is to limit the term that might appear in `slack` or `s_i * q_i` to have degree smaller than the maximum degree of `p` (`maxdeg` in `getmonomialsforcertificate`) but we might also restrict it to be bigger than `mindeg`.

This would give
````julia
function addpolynonnegativeconstraint(m::JuMP.Model, p, domain::BasicSemiAlgebraicSet)
    mindeg, maxdeg = cfld(extrema(map(sum, p.x.Z)), 2) # We might want to add this as a function in MultivariatePolynomials.jl
    for q in domain.p
        mindegq, maxdegq = cfld(extrema(map(sum, q.x.Z)), 2)
        mind = mindeg - mindegq
        maxd = maxdeg - maxdegq
        mind = max(0, Int(floor(mind / 2)))
        maxd = Int(ceil(maxd / 2))
        s = createnonnegativepoly(m, :Gram,  MonomialVector(vars(p), mind:maxd)) # we might also need the handle the case where `p`, `q_i`, ... do not have the same variables so instead of `var(p)` we would have the union of them all
        p -= s*q
    end
    Z = getmonomialsforcertificate(p.x)
    slack = createnonnegativepoly(m, :Gram, Z)
    q = p - slack
    lincons = addpolyeqzeroconstraint(m, q, domain)
    SOSConstraint(slack, lincons, q.x)
end
````

**Comment by joehuchette** [comment]
Maybe I'm mistaken, but couldn't the degree you need for ``s`` to prove nonnegativity be arbitrarily high? Not that it makes too much of a difference, in that case we would need a heuristic way to pick monomials anyway.

I'll make the changes at this point, then we can go about merging this PR and JuliaOpt/PolyJuMP.jl#1 if you approve.

**Comment by blegat** [comment]
It can be arbitrarily high and still it might not be enough because we are doing the quadratic module and not the preorder. I agree, for now we can keep something simple.

**Comment by blegat** [comment]
@joehuchette I added SOSDEMO7 and SOSDEMO8 and made a few changes to this PR and the one in PolyJuMP to make them pass. What do you think of the changes ?

**Comment by joehuchette** [comment]
Looks good to me. Am I correct in my understanding that both this PR and https://github.com/JuliaOpt/PolyJuMP.jl/pull/1 need to be merged simultaneously for both packages to pass on Travis?

**Comment by blegat** [comment]
@joehuchette Yes, they need to be merged simultaneously, we will be forced to merge the two PRs which the checks are failing.

**Comment by joehuchette** [comment]
Cool!

**Pull request merged**
