### PR TITLE
Allow polynomial equality constraint with faux basic semialgebraic set domain

### PR DESCRIPTION
**Pull request by joehuchette**
Relatedly, what would be the way to add the constraint if the semialgebraic part was not empty?

### CODE REVIEW

**Comment by blegat** [comment]
Good question ! This is discussed in #4 . As said there, we could replace the constraint `q(x) == 0` by the 2 constraints `q <= 0` and `q >= 0` if there is at least one inequality.

**Comment by joehuchette** [comment]
Yeah that's all I could think of either. Worth trying, I'll pull it together tomorrow.

**Comment by joehuchette** [comment]
This might be silly, but do you have a good example for a equality polyconstraint? I'm having a hard time coming up with a test case for equality polyconstraint with a domain that's feasible...

**Comment by blegat** [comment]
You can try `x^3 + x^2*y == x` where `x^2 + y^2 >= 1` and `x^2 + y^2 <= 1` :-P

**Comment by joehuchette** [comment]
Lol ya that works

**Comment by joehuchette** [comment]
Travis is misbehaving, gonna merge anyway.

**Pull request merged**
